### ISSUE TITLE
Guidance requested for eval_results.zip and eval_run.sh

### ISSUE THREAD

**Issue by jiankimr** [OSU-NLP-Group/EIA_against_webagent#2]
Thank you for sharing your exceptional research and resources. While following the documentation, I encountered two issues.

- I am unable to locate the **eval_results.zip** file mentioned in the documentation.
- Running eval_run.sh seems to fail, possibly due to missing files.

Could you kindly provide the location or download link for eval_results.zip?
If additional files or steps are needed, your guidance would be greatly appreciated.

Thank you again for your inspiring work and support.

**Comment by lzy37ld** [comment]
Hi @jiankimr , thanks for your interests in EIA.

Can you try to download the file from the [link per README](https://github.com/OSU-NLP-Group/EIA_against_webagent?tab=readme-ov-file#download), which has a file named eval_results.zip. After downloading it, you should be able to run the eval_run.sh successfully.

Please let me know if you run into any other issues!
